apiVersion: v1
kind: Pod
metadata:
  name: myapp-mysql
  labels:
    app: myapp-mysql
spec:
  containers:
  - name: myapp-mysql
    image: mysql
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secrets
          key: ROOT_PASSWORD